baseurl = "https://www.kahlillechelt.com"
languageCode = "en-us"
title = "Kahlil Lechelt's Blog"
googleAnalytics = ""
disqusShortname = ""
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true
summaryLength = 50

[permalinks]
  posts = "/blog/:slug"

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Twitter"
  url = "https://mobile.twitter.com/kahliltweets"
  weight = 2
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
[[menu.main]]
  name = "Archive"
  url = "/archive/"
  weight = 4
[[menu.main]]
  name = "Feed"
  url = "/index.xml"
  weight = 6

[params]
  description = "A blog by Kahlil Lechelt"
  footer = "&copy; [Kahlil Lechelt](https://kahlil.info) 2017 | [Github](https://github.com/kahlil) | [Twitter](https://twitter.com/kahliltweets)"

[outputs]
  home = ["html", "json", "rss"]
  section = ["html", "json", "rss"]

[taxonomies]
  tag = "tags"